require("user.keymaps")
require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.whichkey")
require("user.alpha")
require("user.treesitter")
require("user.nvimtree")
require("user.gitsigns")
require("user.lualine")
require("user.toggleterm")
require("user.bufferline")
require("user.comment")
require("user.hop")

require("impatient")
